name: 'CI'
description: 'Runs the Portfolio React CI'
inputs:
  working-directory:
    description: 'path to working directory'
    default: ./portfolio

runs:
  using: composite
  steps:
    - run: echo "::group::Install Dependencies"
      shell: bash
    - name: Install Dependencies
      run: |
        yarn install
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - run: echo "::endgroup::"
      shell: bash

    - run: echo "::group::Check Style"
      shell: bash
    - name: Check Style
      run: |
        yarn lint
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - run: echo "::endgroup::"
      shell: bash

    - run: echo "::group::Run Tests"
      shell: bash
    - name: Run Tests
      run: |
        yarn test
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - run: echo "::endgroup::"
      shell: bash
