name: 'CI'
description: 'Runs the Portfolio React CI'
runs:
  env:
    working-directory: ./portfolio
  using: composite
  steps:
    - run: echo "::group::Install Dependencies"
      shell: bash
    - name: Install Dependencies
      run: |
        echo ${{ env.working-directory }}
        echo pwd
        yarn install
      working-directory: ./portfolio
      shell: bash
    - run: echo "::endgroup::"
      shell: bash

    - run: echo "::group::Check Style"
      shell: bash
    - name: Check Style
      run: |
        yarn lint
      working-directory: ${{ env.working-directory }}
      shell: bash
    - run: echo "::endgroup::"
      shell: bash

    - run: echo "::group::Run Tests"
      shell: bash
    - name: Run Tests
      run: |
        yarn test
      working-directory: ${{ env.working-directory }}
      shell: bash
    - run: echo "::endgroup::"
      shell: bash
