name: 'CI'
description: 'Runs the Portfolio React CI'

runs:
  using: composite
  steps:
    - run: echo "::group::Install Dependencies"
      shell: bash
    - name: Install Dependencies
      run: |
        cd portfolio
        yarn install
      shell: bash
    - run: echo "::endgroup::"
      shell: bash

    - run: echo "::group::Check Style"
      shell: bash
    - name: Check Style
      run: |
        cd portfolio
        yarn lint
      shell: bash
    - run: echo "::endgroup::"
      shell: bash

    - run: echo "::group::Run Tests"
      shell: bash
    - name: Run Tests
      run: |
        cd portfolio
        yarn test
      shell: bash
    - run: echo "::endgroup::"
      shell: bash
