name: 'CI'
description: 'Runs the Portfolio React CI'

runs:
  steps:
    - name: Install Dependencies
      run: |
        cd portfolio
        yarn install
    - name: Check Style
      run: |
        cd portfolio
        yarn lint
    - name: Run Tests
      run: |
        cd portfolio
        yarn test
