name: Portfolio CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [14]

    steps:
      - uses: actions/checkout@v2

      - name: CI
        uses: .actions/Portfolio-CI@v1

      - name: Deploy
        run: |
          cd portfolio
          yarn deploy